import { comparePassword, generateToken, hashPassword } from "../../application/security/auth.security";
import { AuthRepository } from "../../infrastructure/repositories/auth.repository";
import { User } from "../../domain/auth";
import { Prisma } from "@prisma/client";
import { generateRandomPassword } from "../security/password.utils";
import { sendTemplatedEmail } from "../../../../shared/infrastructure/mailers";
import { environment } from "../../../../config/enviroment";
import { prisma } from "../../../../config/database/db";

interface AuthResponse {
  token: string;
  user: {
    id: string;
    email: string;
    roleId: string;
  };
  generatedPassword?: string;
}

// Datos de registro: unificados en users
interface RegisterUserData {
  email: string;
  password?: string;
  google_id?: string;
  image?: string;
  name?: string;
  last_name?: string;
  phone?: string;
  autoGeneratePassword?: boolean;
}

export class AuthService {

    static prepareAuthResponse(user: User, generatedPassword?: string): AuthResponse {
      const token = generateToken(user);
      const response: AuthResponse = { 
        token,
        user: {
          id: user.id?.toString() || '',
          email: user.email,
          roleId: user.subscription_id?.toString() || ''
        }
      };
      if (generatedPassword) {
        response.generatedPassword = generatedPassword;
      }
      return response;
    }

    static async login(email: string, password: string) {
      const user = await AuthRepository.findUserByEmail(email);
      if (!user) {
        throw new Error('Usuario no encontrado');
      }
      const isValidPassword = comparePassword(password, user.password_hash || '');
      if (!isValidPassword) {
        throw new Error('Contraseña incorrecta');
      }
      user.registerComplete = true;
      const recipientName = user.nombre ?? user.email.split('@')[0];
      await sendTemplatedEmail({
        to: user.email,
        subject: 'Inicio de sesión - Finanzas App',
        recipientName,
        contentText: [
          'hemos detectado un inicio de sesión en tu cuenta.',
          'Si no fuiste tu, por favor cambia tu contraseña inmediatamente.',
          '{{ACTION_BUTTON}}',
          '',
          'Si no solicitaste este cambio, puedes ignorar este correo.',
        ].join('\n'),
        action: {
          title: 'Recuperar contraseña',
          url: `${environment.baseUrl}/forgot-password`,
        },
      });
      return this.prepareAuthResponse(user);
    }

    static async register(userData: RegisterUserData): Promise<AuthResponse> {
      const validateEmail = await AuthRepository.findUserByEmail(userData.email);
      if (validateEmail) {
        throw new Error('Ya existe un usuario con este email');
      }

      let plainPassword = userData.password;
      const isAutoGenerated = userData.autoGeneratePassword || !userData.password;
      if (isAutoGenerated) {
        plainPassword = generateRandomPassword(12);
      }
      const hashedPassword = hashPassword(plainPassword || '');

      // Buscar la suscripción 'Gratuito' por defecto
      const defaultSub = await prisma.subscriptions.findFirst({
        where: { name: 'Gratuito' }
      });

      const userCreateData: Prisma.usersCreateInput = {
        email: userData.email,
        nombre: userData.name || userData.email.split('@')[0],
        password_hash: hashedPassword,
        foto_perfil: userData.image || null,
        google_id: userData.google_id || null,
        estado: 1,
        email_verificado: 0,
        subscription: defaultSub ? { connect: { id: defaultSub.id } } : undefined,
        fecha_creacion: new Date(),
        fecha_modificacion: new Date()
      };

      const newUser = await AuthRepository.createUser(userCreateData);
      if (newUser instanceof Error) {
        throw newUser;
      }

      const createdUser = await AuthRepository.findUserById(newUser.id || BigInt(0));
      if (!createdUser) {
        throw new Error('Error al obtener el usuario creado');
      }
      createdUser.registerComplete = true;

      if (isAutoGenerated && plainPassword) {
        try {
          const userName = createdUser.nombre ?? createdUser.email.split('@')[0];
          const production = process.env.EXPRESS_PRODUCTION?.toLowerCase() === 'true';
          const url = production
            ? `https://${process.env.BASE_URL}`
            : `http://${process.env.BASE_URL_LOCAL}:${Number(process.env.EXPRESS_PORT ?? '3000') + 1}`;
          const loginLink = `${url}/login`;
          await sendTemplatedEmail({
            to: createdUser.email,
            subject: 'Bienvenido a Finanzas App',
            recipientName: userName || createdUser.email.split('@')[0],
            contentText: [
              'Tu cuenta ha sido creada exitosamente.',
              '',
              'Credenciales de acceso:',
              `- Email: ${createdUser.email}`,
              `- Contraseña temporal: ${plainPassword}`,
              '',
              'Te recomendamos cambiar tu contraseña después del primer inicio de sesión.',
            ].join('\n'),
            action: {
              title: 'Ingresar al sistema',
              url: loginLink,
            },
          });
        } catch (emailError) {
          console.error('Error al enviar correo de bienvenida:', emailError);
        }
      }

      return this.prepareAuthResponse(createdUser, isAutoGenerated ? plainPassword : undefined);
    }

    static async googleLogin(googleUser: any) {
      let user = await AuthRepository.findUserByEmail(googleUser.email);

      if (!user) {
        const defaultSub = await prisma.subscriptions.findFirst({
          where: { name: 'Gratuito' }
        });

        const userCreateData: Prisma.usersCreateInput = {
          email: googleUser.email,
          nombre: googleUser.name || googleUser.email.split('@')[0],
          google_id: googleUser.id,
          foto_perfil: googleUser.picture || null,
          email_verificado: 1,
          estado: 1,
          subscription: defaultSub ? { connect: { id: defaultSub.id } } : undefined,
          fecha_creacion: new Date(),
          fecha_modificacion: new Date()
        };
        const newUser = await AuthRepository.createUser(userCreateData);
        if (newUser instanceof Error) {
          throw newUser;
        }
        user = await AuthRepository.findUserByEmail(googleUser.email);
        if (!user) {
          throw new Error('Error al obtener el usuario creado por Google');
        }
      }

      user.registerComplete = true;
      return this.prepareAuthResponse(user);
    }
}
