import { comparePassword, generateToken, hashPassword } from "../../application/security/auth.security";
import { AuthRepository } from "../../infrastructure/repositories/auth.repository";
import { User } from "../../domain/auth";
import { Prisma } from "@prisma/client";
import { generateRandomPassword } from "../security/password.utils";
import { sendTemplatedEmail } from "../../../../shared/infrastructure/mailers";
import { environment } from "../../../../config/enviroment";

interface AuthResponse {
  token: string;
  user: {
    id: string;
    email: string;
    roleId: string;
  };
  generatedPassword?: string;
}

// Datos de registro: users + perfil (user_profiles)
interface RegisterUserData {
  email: string;
  password?: string;
  google_id?: string;
  image?: string;
  name?: string;
  last_name?: string;
  phone?: string;
  autoGeneratePassword?: boolean;
}

export class AuthService {

    static prepareAuthResponse(user: User, generatedPassword?: string): AuthResponse {
      const token = generateToken(user);
      const response: AuthResponse = { 
        token,
        user: {
          id: user.id?.toString() || '',
          email: user.email,
          roleId: user.role_id?.toString() || ''
        }
      };
      if (generatedPassword) {
        response.generatedPassword = generatedPassword;
      }
      return response;
    }

    static async login(email: string, password: string) {
      const user = await AuthRepository.findUserByEmail(email);
      if (!user) {
        throw new Error('Usuario no encontrado');
      }
      const isValidPassword = comparePassword(password, user.password || '');
      if (!isValidPassword) {
        throw new Error('Contraseña incorrecta');
      }
      user.registerComplete = true;
      const recipientName = user.user_profiles?.name ?? user.email.split('@')[0];
      await sendTemplatedEmail({
        to: user.email,
        subject: 'Inicio de Session - IVE',
        recipientName,
        contentText: [
          'hemos detectado un inicio de sesión en tu cuenta.',
          'Si no fuiste tu, por favor cambia tu contraseña inmediatamente.',
          '{{ACTION_BUTTON}}',
          '',
          'Si no solicitaste este cambio, puedes ignorar este correo.',
        ].join('\n'),
        action: {
          title: 'Recuperar contraseña',
          url: `${environment.baseUrl}/forgot-password`,
        },
      });
      return this.prepareAuthResponse(user);
    }

    static async register(userData: RegisterUserData): Promise<AuthResponse> {
      const validateEmail = await AuthRepository.findUserByEmail(userData.email);
      if (validateEmail) {
        throw new Error('Ya existe un usuario con este email');
      }

      let plainPassword = userData.password;
      const isAutoGenerated = userData.autoGeneratePassword || !userData.password;
      if (isAutoGenerated) {
        plainPassword = generateRandomPassword(12);
      }
      const hashedPassword = hashPassword(plainPassword || '');

      const userCreateData: Prisma.usersCreateInput = {
        email: userData.email,
        password: hashedPassword,
        email_verified_at: null,
        created_at: new Date(),
        updated_at: new Date()
      };
      if (userData.google_id) userCreateData.google_id = userData.google_id;
      if (userData.image) userCreateData.image = userData.image;

      const hasProfileData = !!(userData.name || userData.last_name || userData.phone);
      if (hasProfileData) {
        userCreateData.user_profiles = {
          create: {
            name: userData.name ?? null,
            last_name: userData.last_name ?? null,
            phone: userData.phone ?? null,
            created_at: new Date(),
            updated_at: new Date()
          }
        };
      }

      const newUser = await AuthRepository.createUser(userCreateData);
      if (newUser instanceof Error) {
        throw newUser;
      }

      const createdUser = await AuthRepository.findUserById(newUser.id || BigInt(0));
      if (!createdUser) {
        throw new Error('Error al obtener el usuario creado');
      }
      createdUser.registerComplete = true;

      if (isAutoGenerated && plainPassword) {
        try {
          const userName = createdUser.user_profiles?.name ?? createdUser.email.split('@')[0];
          const production = process.env.EXPRESS_PRODUCTION?.toLowerCase() === 'true';
          const url = production
            ? `https://${process.env.BASE_URL}`
            : `http://${process.env.BASE_URL_LOCAL}:${Number(process.env.EXPRESS_PORT ?? '3000') + 1}`;
          const loginLink = `${url}/login`;
          await sendTemplatedEmail({
            to: createdUser.email,
            subject: 'Bienvenido a IVE',
            recipientName: userName || createdUser.email.split('@')[0],
            contentText: [
              'Tu cuenta ha sido creada exitosamente.',
              '',
              'Credenciales de acceso:',
              `- Email: ${createdUser.email}`,
              `- Contraseña temporal: ${plainPassword}`,
              '',
              'Te recomendamos cambiar tu contraseña después del primer inicio de sesión.',
            ].join('\n'),
            action: {
              title: 'Ingresar al sistema',
              url: loginLink,
            },
          });
        } catch (emailError) {
          console.error('Error al enviar correo de bienvenida:', emailError);
        }
      }

      return this.prepareAuthResponse(createdUser, isAutoGenerated ? plainPassword : undefined);
    }

    static async googleLogin(googleUser: any) {
      let user = await AuthRepository.findUserByEmail(googleUser.email);

      if (!user) {
        const userCreateData: Prisma.usersCreateInput = {
          email: googleUser.email,
          google_id: googleUser.id,
          image: googleUser.picture,
          email_verified_at: new Date(),
          created_at: new Date(),
          updated_at: new Date()
        };
        const newUser = await AuthRepository.createUser(userCreateData);
        if (newUser instanceof Error) {
          throw newUser;
        }
        user = await AuthRepository.findUserByEmail(googleUser.email);
        if (!user) {
          throw new Error('Error al obtener el usuario creado por Google');
        }
      }

      user.registerComplete = true;
      return this.prepareAuthResponse(user);
    }
}
